### ISSUE TITLE
Teamname and podname are currently same.

### ISSUE THREAD

**Issue by h3llix** [sdslabs/katana#27]
Here: https://github.com/sdslabs/katana/blob/510752826ebbc92a7d216a896fafbc8327317815/services/sshproviderservice/helper.go#L34-L35

Here team name can be specified by the team themselves. Also, It can be a point of discussion that if somehow one team is unable to participate in the next. Then how are we going to handle that since we are using Daemonsets.

**Comment by Bisht13** [comment]
Fixed
