### ISSUE TITLE
Use docker client to build images

### ISSUE THREAD

**Issue by ashpect** [sdslabs/katana#63]
https://github.com/sdslabs/katana/pull/61/files/d38af68c32955f14646205f4c0bfb646ba81ae88#diff-591148dcd04ed89ed256a23d26a63730eae325a1acc4a9393d9e2016e0884bd0

To use an image in Minikube for deployment, there are three options, none of them are perfect:
One of the method is pointing to the docker inside minikube (or to be technically correct,  the docker volume which Minikube accesses from the outside docker) and then using the docker client.
Here are some helpful links :
https://minikube.sigs.k8s.io/docs/commands/docker-env/
You can try using this thing also  and implementing it. https://github.com/fsouza/go-dockerclient

**Comment by Bisht13** [comment]
Fixed
